// <auto-generated />
using BookVerse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookVerse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803053553_AddCategories")]
    partial class AddCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookVerse.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "James Clear",
                            Category = "Self Help",
                            CoverImage = "atomic-habits.jpg",
                            Description = "A practical guide to building good habits.",
                            Rating = 5.0,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert Kiyosaki",
                            Category = "Finance",
                            CoverImage = "rich-dad-poor-dad.jpg",
                            Description = "A book about money, investing and financial education.",
                            Rating = 5.0,
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            Id = 3,
                            Author = "A.P.J. Abdul Kalam",
                            Category = "Biography",
                            CoverImage = "wings-of-fire.jpg",
                            Description = "The inspiring autobiography of A.P.J. Abdul Kalam.",
                            Rating = 5.0,
                            Title = "Wings of Fire"
                        });
                });

            modelBuilder.Entity("BookVerse.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
